pipeline:
  build:
    image: node:alpine
    commands:
      - npm install
      - npm run build
  test:
    image: node:alpine
    commands:
      - npm install
      - npm run lint
  ecr:
    image: plugins/ecr
    repo: hello-typescript
    secrets: [ ecr_access_key, ecr_secret_key, ecr_registry ]
    tags: "${DRONE_COMMIT_SHA:0:8}"
    file: Dockerfile
    region: ap-southeast-2
    environment:
      - PORT=3000
  rancher:
    image: peloton/drone-rancher
    secrets: [ rancher_url, rancher_access_key, rancher_secret_key, rancher_docker_image ]
    service: services/hello-typescript
    confirm: true
    timeout: 180
