pipeline:
  build:
    image: node:alpine
    commands:
      - npm install
      - npm run build
    environment:
      - PORT=3000
  ecr:
    image: plugins/ecr
    registry: 409735724746.dkr.ecr.ap-southeast-2.amazonaws.com/hello-typescript
    repo: 409735724746.dkr.ecr.ap-southeast-2.amazonaws.com
    secrets: [ ecr_access_key, ecr_secret_key ]
    tags: latest
    file: Dockerfile
  rancher:
    image: peloton/drone-rancher
    url: http://52.64.80.9/v1/projects/1a1291
    access_key: D1925580C6A42A957CB0
    secret_key: Fkd8kHTUSjE9HST5ajuXbvMFPQiW6pgpMsqSDLag
    service: services/hello-typescript
    docker_image: 409735724746.dkr.ecr.ap-southeast-2.amazonaws.com/hello-typescript:latest
    confirm: true
    timeout: 240
