pipeline:
  build:
    image: node:alpine
    commands:
      - npm install
      - npm run build
    environment:
      - PORT=3000
  ecr:
    image: plugins/ecr
    registry: 409735724746.dkr.ecr.ap-southeast-2.amazonaws.com
    repo: hello-typescript
    secrets: [ ecr_access_key, ecr_secret_key ]
    tags: development
    file: Dockerfile
    region: ap-southeast-2
  rancher:
    image: peloton/drone-rancher
    url: http://52.64.80.9
    secrets: [ rancher_access_key, rancher_secret_key ]
    service: services/hello-typescript
    docker_image: 409735724746.dkr.ecr.ap-southeast-2.amazonaws.com/hello-typescript:development
    confirm: true
    timeout: 240
